### ISSUE TITLE
Add an extension for 24.08

### ISSUE THREAD

**Issue by tyllj** [flathub/org.freedesktop.Sdk.Extension.dotnet8#19]
As dotnet development tools move to the freedesktop 24.08 SDK (see https://github.com/flathub/com.jetbrains.Rider/issues/105#issue-2527956256), matching releases of the dotnet SDK extensions are needed as well. 

Similar to https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6/issues/25.

**Comment by Dryadxon** [comment]
With https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet8/commit/c6cb7a37373d6987f2c1c0cb0b90df3c43d072ff it should be resolved, just waiting for the first build to be available before closing this issue.
