### ISSUE TITLE
Will there be a dotnet 9 extension?

### ISSUE THREAD

**Issue by hendrikmennen** [flathub/org.freedesktop.Sdk.Extension.dotnet8#25]
Since the extension for dotnet7 is not available aswell, I am wondering if only LTS releases get an extension?

If not, is someone working on this and can give some information? 
I would like to release my IDE with .net 9 https://github.com/flathub/com.one_ware.OneWare/blob/master/com.one_ware.OneWare.yml

**Comment by Dryadxon** [comment]
> Since the extension for dotnet7 is not available aswell, I am wondering if only LTS releases get an extension?

I don't plan to publish an extension for .NET 9, but anyone interested can step up and do so since it's volunteer-based.

> If not, is someone working on this and can give some information? I would like to release my IDE with .net 9 https://github.com/flathub/com.one_ware.OneWare/blob/master/com.one_ware.OneWare.yml

I don't think someone it's working on it; otherwise, there would be a PR like the one for [.NET 8](https://github.com/flathub/flathub/pull/4534).

**Comment by hendrikmennen** [comment]
Okay thats unfortunate. I never did anything with flatpak extensions but I guess it should be mostly copy paste with some modifications. I will see if I can do it once I have time

**Comment by hendrikmennen** [comment]
I tried to do it myself https://github.com/flathub/flathub/pull/5860

**Comment by Dryadxon** [comment]
@HendrikMennen I'll close this issue since [.NET 9](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet9) has been added to flathub.
