### ISSUE TITLE
Include `Microsoft.NET.ILLink.Tasks` (+ runtimes?) in the SDK extension

### ISSUE THREAD

**Issue by theCapypara** [flathub/org.freedesktop.Sdk.Extension.dotnet8#26]
See also https://github.com/flatpak/flatpak-builder-tools/issues/420

Currently it is not possible to actually use this SDK extension for common .NET apps with the generator, as most apps will need `Microsoft.NET.ILLink.Tasks` in a version matching the exact runtime version but the generator is currently unable to fetch that due to the issue linked above (`dotnet restore` does not download it, even if required for `dotnet publish`).

Consider shipping `Microsoft.NET.ILLink.Tasks` included with the SDK extension to side-step the issue-

Additionally also consider to ship the runtime packages, since those are also linked to the exact compiler version, so even a patch update of the SDK currently breaks existing apps unless they re-generate sources using the generator and manually fix `Microsoft.NET.ILLink.Tasks` (see above).

**Comment by Dryadxon** [comment]
It should be enough to follow the instructions on this repo's [README](https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet8#publishing-self-contained-app-and-trimmed-binaries), adding the following to the `sources.json`:

```json
{
    "type": "file",
    "url": "https://api.nuget.org/v3-flatcontainer/microsoft.net.illink.tasks/8.0.11/microsoft.net.illink.tasks.8.0.11.nupkg",
    "sha512": "043527c762d2bfc0962b75806cf9cd5adedd79574b067e1567964d512460e1637f5a2d71f8ce16420776cab5beaa7492479965f402a158d52c8865567fe3ac69",
    "dest": "nuget-sources",
    "dest-filename": "microsoft.net.illink.tasks.8.0.nupkg",
    "x-checker-data": {
        "type": "html",
        "url": "https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/8.0/latest.version",
        "version-pattern": "^([\\d\\.a-z-]+)$",
        "url-template": "https://api.nuget.org/v3-flatcontainer/microsoft.net.illink.tasks/$version/microsoft.net.illink.tasks.$version.nupkg"
    }
}
```
Then you should be able to publish .NET apps with generators and be notified by @flathubbot for each NuGet package with `x-checker-data` when a new release it's available.

**Comment by theCapypara** [comment]
We are doing this (minus the checker, we are not using Flathub), but the problem is, that we still need to update this every time a new patch release of .NET is released and added to this SDK extension, this is really not all that ideal.

**Comment by Dryadxon** [comment]
> We are doing this (minus the checker, we are not using Flathub), but the problem is, that we still need to update this every time a new patch release of .NET is released and added to this SDK extension, this is really not all that ideal.

The issue was, correct me if I'm wrong, that `dotnet publish` didn't allow more than one `--source NUGET_DIR`, so the runtime had to be included manually with the other dependencies, but I tested a few minutes ago that at least with the latest versions, even if listing multiple directories it's not documented, that `dotnet publish --source YOUR_NUGETS --source SDK_PROVIDED_NUGETS` works. As soon as I can, I prepare a PR for each branch.

**Comment by Dryadxon** [comment]
@theCapypara let me know if #27 fixes it.

**Comment by theCapypara** [comment]
Thanks a lot! I'll probably only be able to do it on Wednesday but I'll try to give you feedback on this ASAP.

**Comment by hendrikmennen** [comment]
I am not sure if this is directly related, but I had issues with my runtime for my Avalonia App. I managed to fix it by adding `<SelfContained>true</SelfContained>` to the csproj. After that the Genereator (or dotnet restore) downloaded all the necessary packages on restore.

**Comment by Dryadxon** [comment]
> I am not sure if this is directly related, but I had issues with my runtime for my Avalonia App. I managed to fix it by adding `<SelfContained>true</SelfContained>` to the csproj. After that the Genereator (or dotnet restore) downloaded all the necessary packages on restore.

Can I take a look at it? It might be related, since it uses source generators for some features.

**Comment by hendrikmennen** [comment]
> > I am not sure if this is directly related, but I had issues with my runtime for my Avalonia App. I managed to fix it by adding `<SelfContained>true</SelfContained>` to the csproj. After that the Genereator (or dotnet restore) downloaded all the necessary packages on restore.
> 
> Can I take a look at it? It might be related, since it uses source generators for some features.

A look at my project? https://github.com/one-ware/OneWare

I automated the whole flathub release process using the flatpak dotnet generator, as seen here: https://github.com/one-ware/OneWare/blob/main/.github/workflows/publish-studio-linux-flathub.yml

Even though the pipeline currently fails until the net 9 sdk extension is released.

**Comment by Dryadxon** [comment]
> > > I am not sure if this is directly related, but I had issues with my runtime for my Avalonia App. I managed to fix it by adding `<SelfContained>true</SelfContained>` to the csproj. After that the Genereator (or dotnet restore) downloaded all the necessary packages on restore.
> > 
> > 
> > Can I take a look at it? It might be related, since it uses source generators for some features.
> 
> A look at my project? https://github.com/one-ware/OneWare
> 
> I automated the whole flathub release process using the flatpak dotnet generator, as seen here: https://github.com/one-ware/OneWare/blob/main/.github/workflows/publish-studio-linux-flathub.yml
> 
> Even though the pipeline currently fails until the net 9 sdk extension is released.

I think #27 with an updated `dotnet publish --source YOUR_NUGETS --source SDK_NUGETS` should build fine even without `<SelfContained>true</SelfContained>`. I'll test ASAP.

**Comment by Dryadxon** [comment]
@HendrikMennen I tested your project with #27, removing `<SelfContained>true</SelfContained>` and changing the `build-arguments` property in the Flathub manifest, and the build failed because `microsoft.netcore.app.crossgen2` was missing, after adding it all worked like a charm, I'll update the PR by adding that NuGet.
I sincerely hope that no more NuGets will be needed in the future.
